window.UI_LAB_THEMES = [
  {
    id: "molten-glass",
    name: "Molten Glass",
    desc: "Vidro quente translúcido",
    tags: "Glassmorphism · calor · blur",
    group: "pure",
    glass: true,
    feel: "molten",
    chip: "linear-gradient(135deg,#e89a3c,#7ed4c8)",
    eyebrow: "Molten glass atelier",
    title: "Vidro que ainda respira calor.",
    lede: "Painéis foscos de verdade — blur, borda fina e luz quente por trás do vidro.",
  },
  {
    id: "glassmorphism",
    name: "Glassmorphism",
    desc: "Frosted glass clássico",
    tags: "Glassmorphism · frosted · dark",
    group: "pure",
    glass: true,
    feel: "molten",
    chip: "linear-gradient(135deg,#1a1a1e,#8a9bb0)",
    eyebrow: "Frosted interface",
    title: "Vidro fosco sobre metal cromado.",
    lede: "Painéis quase invisíveis com blur pesado — o glassmorphism da referência, em movimento.",
  },
  {
    id: "neumorphism",
    name: "Neumorphism",
    desc: "Soft UI embutido",
    tags: "Neumorphism · soft · relief",
    group: "pure",
    glass: false,
    feel: "soft",
    chip: "linear-gradient(145deg,#e6e9ef,#c5c9d2)",
    eyebrow: "Soft interface",
    title: "Relevo suave, quase tátil.",
    lede: "Luz e sombra internas criam botões que parecem esculpidos no próprio fundo.",
  },
  {
    id: "minimalism",
    name: "Minimalism",
    desc: "Redução radical",
    tags: "Minimalism · whitespace · type",
    group: "pure",
    glass: false,
    feel: "rigid",
    chip: "linear-gradient(135deg,#fff,#111)",
    eyebrow: "Less, still less",
    title: "Só o que precisa existir.",
    lede: "Sem sombra teatral, sem ornamento. Tipografia, espaço e contraste fazem o trabalho.",
  },
  {
    id: "dark-tech",
    name: "Dark Tech",
    desc: "Terminal & neon",
    tags: "Dark Tech · mono · grid",
    group: "pure",
    glass: false,
    feel: "snap",
    chip: "linear-gradient(135deg,#07090d,#3dff9a)",
    eyebrow: "systems/online",
    title: "Interfaces que brilham no escuro.",
    lede: "Grid sutil, accent ácido e tipografia mono — vibe de console e produto developer.",
  },
  {
    id: "frutiger-aero",
    name: "Frutiger Aero",
    desc: "Glossy Y2K utopia",
    tags: "Frutiger Aero · gloss · sky",
    group: "pure",
    glass: true,
    feel: "jelly",
    chip: "linear-gradient(180deg,#a8d8f0,#6ee0a8)",
    eyebrow: "Welcome to 2007",
    title: "Céu de vidro e botões brilhantes.",
    lede: "Gradientes aqua, highlights especulares e aquela esperança digital do início dos anos 2000.",
  },
  {
    id: "neobrutalism",
    name: "Neobrutalism",
    desc: "Maximalismo gen-z",
    tags: "Neobrutalism · Maximalism · bold",
    group: "pure",
    glass: false,
    feel: "snap",
    chip: "linear-gradient(135deg,#fff45a,#ff3d00,#00e5ff)",
    eyebrow: "LOUD BY DESIGN",
    title: "Bordas grossas. Cores gritantes.",
    lede: "Sombras hard-offset, tipografia de cartaz e zero vergonha de ocupar o espaço.",
  },
  {
    id: "skeuomorphism",
    name: "Skeuomorphism",
    desc: "Materiais reais",
    tags: "Skeuomorphism · wood · metal",
    group: "pure",
    glass: false,
    feel: "heavy",
    chip: "linear-gradient(180deg,#f5e6d3,#8b4513)",
    eyebrow: "Crafted surfaces",
    title: "Parece madeira. Parece metal.",
    lede: "Gradientes que imitam materiais físicos — o encanto pré-flat do software tátil.",
  },
  {
    id: "gradient-mesh",
    name: "Gradient Mesh",
    desc: "Mesh colorido",
    tags: "Gradient Mesh · aurora · fluid",
    group: "pure",
    glass: true,
    feel: "jelly",
    chip: "linear-gradient(135deg,#ff6ad5,#6a9fff,#00d4c8)",
    eyebrow: "Color field UI",
    title: "Cor como arquitetura.",
    lede: "Manchas de mesh se misturam atrás de superfícies translúcidas — UI como pintura digital.",
  },
  {
    id: "enterprise",
    name: "Enterprise Clean",
    desc: "SaaS corporativo",
    tags: "Enterprise · B2B · clean",
    group: "pure",
    glass: false,
    feel: "rigid",
    chip: "linear-gradient(135deg,#f4f6f9,#2563eb)",
    eyebrow: "Trusted by teams",
    title: "Clareza que escala com o time.",
    lede: "Azul confiável, cards leves e hierarquia previsível — o visual de produtos B2B maduros.",
  },
  {
    id: "claymorphism",
    name: "Claymorphism",
    desc: "Argila 3D macia",
    tags: "Claymorphism · soft 3D · playful",
    group: "pure",
    glass: false,
    feel: "soft",
    chip: "linear-gradient(145deg,#ffd6e7,#b8e0ff,#d4f5c4)",
    eyebrow: "Squishy surfaces",
    title: "UI que parece massa de modelar.",
    lede: "Volumes pastéis extrudados, cantos generosos e sombras internas — o primo brincalhão do neumorphism.",
  },
  {
    id: "swiss",
    name: "Swiss Style",
    desc: "Grade internacional",
    tags: "Swiss · editorial · grid",
    group: "pure",
    glass: false,
    feel: "rigid",
    chip: "linear-gradient(135deg,#f5f5f5,#e30613)",
    eyebrow: "International Typographic",
    title: "Ordem, eixo e um vermelho preciso.",
    lede: "Grid rigoroso, tipografia editorial e espaço negativo como estrutura — a escola suíça em pixels.",
  },
  {
    id: "vaporwave",
    name: "Vaporwave",
    desc: "Retro-futuro nostálgico",
    tags: "Vaporwave · CRT · nostalgia",
    group: "pure",
    glass: false,
    feel: "jelly",
    chip: "linear-gradient(135deg,#ff71ce,#01cdfe,#b967ff)",
    eyebrow: "ＡＥＳＴＨＥＴＩＣ",
    title: "Rosa, ciano e o eco dos anos 80.",
    lede: "Scanlines, neon pastel e tipografia CRT — nostalgia digital com insolação de shopping mall.",
  },
  {
    id: "memphis",
    name: "Memphis",
    desc: "Geometria anos 80",
    tags: "Memphis · pattern · playful",
    group: "pure",
    glass: false,
    feel: "snap",
    chip: "linear-gradient(135deg,#ff6b6b,#ffe66d,#4ecdc4)",
    eyebrow: "Pattern party",
    title: "Zigzag, bolinha e cor sem medo.",
    lede: "O design italiano dos 80 em UI: formas geométricas, contraste alto e ritmo irregular.",
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    desc: "Neon de megacidade",
    tags: "Cyberpunk · neon · noir",
    group: "pure",
    glass: true,
    feel: "snap",
    chip: "linear-gradient(135deg,#0a0014,#ff2a6d,#05d9e8)",
    eyebrow: "night/city/online",
    title: "Magenta sob chuva de neon.",
    lede: "Noir digital com accents elétricos — glass escuro, tipografia agressiva e brilho de rua.",
  },
  {
    id: "molten-dark-luxury",
    name: "Molten Dark Luxury",
    desc: "Glass + Dark + Luxe",
    tags: "Molten Glass · Dark Tech · Luxury Minimal",
    group: "mix",
    glass: true,
    feel: "molten",
    chip: "linear-gradient(135deg,#0c0b0a,#d4a574)",
    eyebrow: "Quiet heat",
    title: "Luxo escuro com brasa de vidro.",
    lede: "Minimalismo luxuoso encontra molten glass e dark tech — ouro fosco sobre carvão.",
  },
  {
    id: "linear-bento",
    name: "Linear Bento",
    desc: "Linear + Bento + Mini",
    tags: "Linear-inspired · Bento UI · Minimalism",
    group: "mix",
    glass: false,
    feel: "rigid",
    chip: "linear-gradient(135deg,#0f0f10,#5e6ad2)",
    eyebrow: "Product craft",
    title: "Densidade elegante em caixas.",
    lede: "A precisão do Linear, a grade bento e o silêncio do minimalismo — UI de ferramenta moderna.",
  },
  {
    id: "neo-organic-max",
    name: "Organic Brutal",
    desc: "Neo + Organic + Max",
    tags: "Neobrutalism · Organic UI · Maximalism",
    group: "mix",
    glass: false,
    feel: "snap",
    chip: "linear-gradient(135deg,#ff8fab,#b8f205,#7bdff2)",
    eyebrow: "WILD FORMS",
    title: "Brutalismo com curvas vivas.",
    lede: "Offsets duros, raios irregulares e cores de festa — maximalismo orgânico sem pedir licença.",
  },
  {
    id: "aero-glass",
    name: "Aero Glass",
    desc: "Aero + Glassmorphism",
    tags: "Frutiger Aero · Glassmorphism",
    group: "mix",
    glass: true,
    feel: "jelly",
    chip: "linear-gradient(135deg,#7ec0e8,#48c9a0)",
    eyebrow: "Sky through glass",
    title: "Vidro fosco sob céu utópico.",
    lede: "O gloss do Frutiger Aero atravessa painéis glass — nostalgia 2000 com blur moderno.",
  },
  {
    id: "soft-enterprise",
    name: "Soft Enterprise",
    desc: "Neo + Enterprise",
    tags: "Neumorphism · Enterprise Clean",
    group: "mix",
    glass: false,
    feel: "soft",
    chip: "linear-gradient(145deg,#eef1f6,#3b82f6)",
    eyebrow: "Gentle productivity",
    title: "Corporativo, mas macio.",
    lede: "A confiança do enterprise com o relevo neumórfico — dashboards que pedem para tocar.",
  },
  {
    id: "skeuo-luxe",
    name: "Skeuo Luxe Mesh",
    desc: "Skeuo + Mesh + Luxe",
    tags: "Skeuomorphism · Gradient Mesh · Luxury",
    group: "mix",
    glass: true,
    feel: "heavy",
    chip: "linear-gradient(135deg,#1a1220,#d4af78,#8b5a9e)",
    eyebrow: "Gilded aurora",
    title: "Metal precioso sob aurora.",
    lede: "Skeuomorphism dourado dança com mesh violeta — opulência digital com profundidade de material.",
  },
  {
    id: "brutal-tech",
    name: "Brutal Tech",
    desc: "Neo + Dark Tech",
    tags: "Neobrutalism · Dark Tech",
    group: "mix",
    glass: false,
    feel: "snap",
    chip: "linear-gradient(135deg,#0a0a0a,#e8ff47,#ff2d55)",
    eyebrow: "HACK THE FRAME",
    title: "Terminal com atitude de cartaz.",
    lede: "Mono ácido, offsets pink e grid brutal — dark tech que grita em vez de sussurrar.",
  },
  {
    id: "vapor-glass",
    name: "Vapor Glass",
    desc: "Vapor + Glass + Dark",
    tags: "Vaporwave · Glassmorphism · Dark Tech",
    group: "mix",
    glass: true,
    feel: "molten",
    chip: "linear-gradient(135deg,#1a0a24,#ff71ce,#01cdfe)",
    eyebrow: "Neon through frost",
    title: "Mall nostálgico sob vidro escuro.",
    lede: "Vaporwave encontra glassmorphism e dark tech — neon pastel refratado em painéis foscos.",
  },
  {
    id: "swiss-brutal",
    name: "Swiss Brutal",
    desc: "Swiss + Neo + Editorial",
    tags: "Swiss Style · Neobrutalism · Editorial",
    group: "mix",
    glass: false,
    feel: "snap",
    chip: "linear-gradient(135deg,#f2f2f2,#e30613,#111)",
    eyebrow: "GRID WITH TEETH",
    title: "Grade suíça, soco brutalista.",
    lede: "Eixo tipográfico internacional com bordas grossas e offset — editorial que não pede licença.",
  },
  {
    id: "molten-clay",
    name: "Molten Clay",
    desc: "Glass + Clay + Soft",
    tags: "Molten Glass · Claymorphism · Soft",
    group: "mix",
    glass: true,
    feel: "molten",
    chip: "linear-gradient(135deg,#ffb08a,#ff8fb8,#7ed4c8)",
    eyebrow: "Warm dough glass",
    title: "Vidro quente com alma de argila.",
    lede: "Translucidez molten encontra volumes clay — superfícies que pedem para apertar.",
  },
  {
    id: "cyber-glass",
    name: "Cyber Glass",
    desc: "Cyber + Glass + Dark",
    tags: "Cyberpunk · Glassmorphism · Dark Tech",
    group: "mix",
    glass: true,
    feel: "snap",
    chip: "linear-gradient(135deg,#050010,#ff2a6d,#05d9e8)",
    eyebrow: "rain on glass",
    title: "Neon atrás do vidro molhado.",
    lede: "Cyberpunk sob glassmorphism — painéis foscos cortando sinalizadores da cidade.",
  },
  {
    id: "memphis-brutal",
    name: "Memphis Brutal",
    desc: "Memphis + Neo + Max",
    tags: "Memphis · Neobrutalism · Maximalism",
    group: "mix",
    glass: false,
    feel: "snap",
    chip: "linear-gradient(135deg,#ffe66d,#ff6b6b,#111)",
    eyebrow: "PARTY OFFSET",
    title: "Padrão 80s com soco gen-z.",
    lede: "Memphis encontra neobrutalismo — geometria festiva com sombra dura de cartaz.",
  },
];

window.UI_LAB_FEELS = {
  molten: { stiffness: 0.06, damping: 0.78, hover: 1.1, press: 0.92, jiggle: 18, elastic: true },
  soft: { stiffness: 0.1, damping: 0.82, hover: 1.06, press: 0.94, jiggle: 10, elastic: true },
  jelly: { stiffness: 0.08, damping: 0.72, hover: 1.12, press: 0.88, jiggle: 22, elastic: true },
  snap: { stiffness: 0.35, damping: 0.55, hover: 1.04, press: 0.96, jiggle: 8, elastic: false },
  rigid: { stiffness: 0.45, damping: 0.7, hover: 1.02, press: 0.98, jiggle: 4, elastic: false },
  heavy: { stiffness: 0.12, damping: 0.88, hover: 1.05, press: 0.95, jiggle: 6, elastic: true },
};
