window.UI_LAB_THEMES = [
  {
    id: "molten-glass",
    name: "Molten Glass",
    desc: "Glassmorphism líquido",
    tags: "Glassmorphism · calor · blur",
    group: "pure",
    chip: "linear-gradient(135deg,#e89a3c,#7ed4c8)",
    eyebrow: "Molten glass atelier",
    title: "Vidro que ainda respira calor.",
    lede: "Camadas translúcidas, bordas quentes e luz que escorre — glassmorphism com temperamento de forno.",
  },
  {
    id: "neumorphism",
    name: "Neumorphism",
    desc: "Soft UI embutido",
    tags: "Neumorphism · soft · relief",
    group: "pure",
    chip: "linear-gradient(145deg,#e6e9ef,#c5c9d2)",
    eyebrow: "Soft interface",
    title: "Relevo suave, quase tátil.",
    lede: "Luz e sombra internas criam botões que parecem esculpidos no próprio fundo.",
  },
  {
    id: "minimalism",
    name: "Minimalism",
    desc: "Redução radical",
    tags: "Minimalism · whitespace · type",
    group: "pure",
    chip: "linear-gradient(135deg,#fff,#111)",
    eyebrow: "Less, still less",
    title: "Só o que precisa existir.",
    lede: "Sem sombra teatral, sem ornamento. Tipografia, espaço e contraste fazem o trabalho.",
  },
  {
    id: "dark-tech",
    name: "Dark Tech",
    desc: "Terminal & neon",
    tags: "Dark Tech · mono · grid",
    group: "pure",
    chip: "linear-gradient(135deg,#07090d,#3dff9a)",
    eyebrow: "systems/online",
    title: "Interfaces que brilham no escuro.",
    lede: "Grid sutil, accent ácido e tipografia mono — vibe de console e produto developer.",
  },
  {
    id: "frutiger-aero",
    name: "Frutiger Aero",
    desc: "Glossy Y2K utopia",
    tags: "Frutiger Aero · gloss · sky",
    group: "pure",
    chip: "linear-gradient(180deg,#a8d8f0,#6ee0a8)",
    eyebrow: "Welcome to 2007",
    title: "Céu de vidro e botões brilhantes.",
    lede: "Gradientes aqua, highlights especulares e aquela esperança digital do início dos anos 2000.",
  },
  {
    id: "neobrutalism",
    name: "Neobrutalism",
    desc: "Maximalismo gen-z",
    tags: "Neobrutalism · Maximalism · bold",
    group: "pure",
    chip: "linear-gradient(135deg,#fff45a,#ff3d00,#00e5ff)",
    eyebrow: "LOUD BY DESIGN",
    title: "Bordas grossas. Cores gritantes.",
    lede: "Sombras hard-offset, tipografia de cartaz e zero vergonha de ocupar o espaço.",
  },
  {
    id: "skeuomorphism",
    name: "Skeuomorphism",
    desc: "Materiais reais",
    tags: "Skeuomorphism · wood · metal",
    group: "pure",
    chip: "linear-gradient(180deg,#f5e6d3,#8b4513)",
    eyebrow: "Crafted surfaces",
    title: "Parece madeira. Parece metal.",
    lede: "Gradientes que imitam materiais físicos — o encanto pré-flat do software tátil.",
  },
  {
    id: "gradient-mesh",
    name: "Gradient Mesh",
    desc: "Mesh colorido",
    tags: "Gradient Mesh · aurora · fluid",
    group: "pure",
    chip: "linear-gradient(135deg,#ff6ad5,#6a9fff,#00d4c8)",
    eyebrow: "Color field UI",
    title: "Cor como arquitetura.",
    lede: "Manchas de mesh se misturam atrás de superfícies translúcidas — UI como pintura digital.",
  },
  {
    id: "enterprise",
    name: "Enterprise Clean",
    desc: "SaaS corporativo",
    tags: "Enterprise · B2B · clean",
    group: "pure",
    chip: "linear-gradient(135deg,#f4f6f9,#2563eb)",
    eyebrow: "Trusted by teams",
    title: "Clareza que escala com o time.",
    lede: "Azul confiável, cards leves e hierarquia previsível — o visual de produtos B2B maduros.",
  },
  {
    id: "claymorphism",
    name: "Claymorphism",
    desc: "Argila 3D macia",
    tags: "Claymorphism · soft 3D · playful",
    group: "pure",
    chip: "linear-gradient(145deg,#ffd6e7,#b8e0ff,#d4f5c4)",
    eyebrow: "Squishy surfaces",
    title: "UI que parece massa de modelar.",
    lede: "Volumes pastéis extrudados, cantos generosos e sombras internas — o primo brincalhão do neumorphism.",
  },
  {
    id: "swiss",
    name: "Swiss Style",
    desc: "Grade internacional",
    tags: "Swiss · editorial · grid",
    group: "pure",
    chip: "linear-gradient(135deg,#f5f5f5,#e30613)",
    eyebrow: "International Typographic",
    title: "Ordem, eixo e um vermelho preciso.",
    lede: "Grid rigoroso, tipografia editorial e espaço negativo como estrutura — a escola suíça em pixels.",
  },
  {
    id: "vaporwave",
    name: "Vaporwave",
    desc: "Retro-futuro nostálgico",
    tags: "Vaporwave · CRT · nostalgia",
    group: "pure",
    chip: "linear-gradient(135deg,#ff71ce,#01cdfe,#b967ff)",
    eyebrow: "ＡＥＳＴＨＥＴＩＣ",
    title: "Rosa, ciano e o eco dos anos 80.",
    lede: "Scanlines, neon pastel e tipografia CRT — nostalgia digital com insolação de shopping mall.",
  },
  {
    id: "molten-dark-luxury",
    name: "Molten Dark Luxury",
    desc: "Glass + Dark + Luxe",
    tags: "Molten Glass · Dark Tech · Luxury Minimal",
    group: "mix",
    chip: "linear-gradient(135deg,#0c0b0a,#d4a574)",
    eyebrow: "Quiet heat",
    title: "Luxo escuro com brasa de vidro.",
    lede: "Minimalismo luxuoso encontra molten glass e dark tech — ouro fosco sobre carvão.",
  },
  {
    id: "linear-bento",
    name: "Linear Bento",
    desc: "Linear + Bento + Mini",
    tags: "Linear-inspired · Bento UI · Minimalism",
    group: "mix",
    chip: "linear-gradient(135deg,#0f0f10,#5e6ad2)",
    eyebrow: "Product craft",
    title: "Densidade elegante em caixas.",
    lede: "A precisão do Linear, a grade bento e o silêncio do minimalismo — UI de ferramenta moderna.",
  },
  {
    id: "neo-organic-max",
    name: "Organic Brutal",
    desc: "Neo + Organic + Max",
    tags: "Neobrutalism · Organic UI · Maximalism",
    group: "mix",
    chip: "linear-gradient(135deg,#ff8fab,#b8f205,#7bdff2)",
    eyebrow: "WILD FORMS",
    title: "Brutalismo com curvas vivas.",
    lede: "Offsets duros, raios irregulares e cores de festa — maximalismo orgânico sem pedir licença.",
  },
  {
    id: "aero-glass",
    name: "Aero Glass",
    desc: "Aero + Glassmorphism",
    tags: "Frutiger Aero · Glassmorphism",
    group: "mix",
    chip: "linear-gradient(135deg,#7ec0e8,#48c9a0)",
    eyebrow: "Sky through glass",
    title: "Vidro fosco sob céu utópico.",
    lede: "O gloss do Frutiger Aero atravessa painéis glass — nostalgia 2000 com blur moderno.",
  },
  {
    id: "soft-enterprise",
    name: "Soft Enterprise",
    desc: "Neo + Enterprise",
    tags: "Neumorphism · Enterprise Clean",
    group: "mix",
    chip: "linear-gradient(145deg,#eef1f6,#3b82f6)",
    eyebrow: "Gentle productivity",
    title: "Corporativo, mas macio.",
    lede: "A confiança do enterprise com o relevo neumórfico — dashboards que pedem para tocar.",
  },
  {
    id: "skeuo-luxe",
    name: "Skeuo Luxe Mesh",
    desc: "Skeuo + Mesh + Luxe",
    tags: "Skeuomorphism · Gradient Mesh · Luxury",
    group: "mix",
    chip: "linear-gradient(135deg,#1a1220,#d4af78,#8b5a9e)",
    eyebrow: "Gilded aurora",
    title: "Metal precioso sob aurora.",
    lede: "Skeuomorphism dourado dança com mesh violeta — opulência digital com profundidade de material.",
  },
  {
    id: "brutal-tech",
    name: "Brutal Tech",
    desc: "Neo + Dark Tech",
    tags: "Neobrutalism · Dark Tech",
    group: "mix",
    chip: "linear-gradient(135deg,#0a0a0a,#e8ff47,#ff2d55)",
    eyebrow: "HACK THE FRAME",
    title: "Terminal com atitude de cartaz.",
    lede: "Mono ácido, offsets pink e grid brutal — dark tech que grita em vez de sussurrar.",
  },
  {
    id: "vapor-glass",
    name: "Vapor Glass",
    desc: "Vapor + Glass + Dark",
    tags: "Vaporwave · Glassmorphism · Dark Tech",
    group: "mix",
    chip: "linear-gradient(135deg,#1a0a24,#ff71ce,#01cdfe)",
    eyebrow: "Neon through frost",
    title: "Mall nostálgico sob vidro escuro.",
    lede: "Vaporwave encontra glassmorphism e dark tech — neon pastel refratado em painéis foscos.",
  },
  {
    id: "swiss-brutal",
    name: "Swiss Brutal",
    desc: "Swiss + Neo + Editorial",
    tags: "Swiss Style · Neobrutalism · Editorial",
    group: "mix",
    chip: "linear-gradient(135deg,#f2f2f2,#e30613,#111)",
    eyebrow: "GRID WITH TEETH",
    title: "Grade suíça, soco brutalista.",
    lede: "Eixo tipográfico internacional com bordas grossas e offset — editorial que não pede licença.",
  },
];
